//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pike13Zoom.Blueface {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning", ConfigurationName="Blueface.SMSAppSOAPProxySoap")]
    public interface SMSAppSOAPProxySoap {
        
        // CODEGEN: Generating message contract since message IsAliveSecureRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://azaclauson.com/webservices/pbx/provisioning/IsAliveSecure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Pike13Zoom.Blueface.IsAliveSecureResponse IsAliveSecure(Pike13Zoom.Blueface.IsAliveSecureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://azaclauson.com/webservices/pbx/provisioning/IsAliveSecure", ReplyAction="*")]
        System.Threading.Tasks.Task<Pike13Zoom.Blueface.IsAliveSecureResponse> IsAliveSecureAsync(Pike13Zoom.Blueface.IsAliveSecureRequest request);
        
        // CODEGEN: Generating message contract since message SendSMSRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://azaclauson.com/webservices/pbx/provisioning/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Pike13Zoom.Blueface.SendSMSResponse SendSMS(Pike13Zoom.Blueface.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://azaclauson.com/webservices/pbx/provisioning/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Pike13Zoom.Blueface.SendSMSResponse> SendSMSAsync(Pike13Zoom.Blueface.SendSMSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning")]
    public partial class SoapAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAliveSecure", WrapperNamespace="http://azaclauson.com/webservices/pbx/provisioning", IsWrapped=true)]
    public partial class IsAliveSecureRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning")]
        public Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader;
        
        public IsAliveSecureRequest() {
        }
        
        public IsAliveSecureRequest(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader) {
            this.SoapAuthHeader = SoapAuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAliveSecureResponse", WrapperNamespace="http://azaclauson.com/webservices/pbx/provisioning", IsWrapped=true)]
    public partial class IsAliveSecureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning", Order=0)]
        public bool IsAliveSecureResult;
        
        public IsAliveSecureResponse() {
        }
        
        public IsAliveSecureResponse(bool IsAliveSecureResult) {
            this.IsAliveSecureResult = IsAliveSecureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS", WrapperNamespace="http://azaclauson.com/webservices/pbx/provisioning", IsWrapped=true)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning")]
        public Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning", Order=0)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning", Order=1)]
        public string message;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader, string destination, string message) {
            this.SoapAuthHeader = SoapAuthHeader;
            this.destination = destination;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSResponse", WrapperNamespace="http://azaclauson.com/webservices/pbx/provisioning", IsWrapped=true)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://azaclauson.com/webservices/pbx/provisioning", Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSAppSOAPProxySoapChannel : Pike13Zoom.Blueface.SMSAppSOAPProxySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSAppSOAPProxySoapClient : System.ServiceModel.ClientBase<Pike13Zoom.Blueface.SMSAppSOAPProxySoap>, Pike13Zoom.Blueface.SMSAppSOAPProxySoap {
        
        public SMSAppSOAPProxySoapClient() {
        }
        
        public SMSAppSOAPProxySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSAppSOAPProxySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSAppSOAPProxySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSAppSOAPProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pike13Zoom.Blueface.IsAliveSecureResponse Pike13Zoom.Blueface.SMSAppSOAPProxySoap.IsAliveSecure(Pike13Zoom.Blueface.IsAliveSecureRequest request) {
            return base.Channel.IsAliveSecure(request);
        }
        
        public bool IsAliveSecure(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader) {
            Pike13Zoom.Blueface.IsAliveSecureRequest inValue = new Pike13Zoom.Blueface.IsAliveSecureRequest();
            inValue.SoapAuthHeader = SoapAuthHeader;
            Pike13Zoom.Blueface.IsAliveSecureResponse retVal = ((Pike13Zoom.Blueface.SMSAppSOAPProxySoap)(this)).IsAliveSecure(inValue);
            return retVal.IsAliveSecureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pike13Zoom.Blueface.IsAliveSecureResponse> Pike13Zoom.Blueface.SMSAppSOAPProxySoap.IsAliveSecureAsync(Pike13Zoom.Blueface.IsAliveSecureRequest request) {
            return base.Channel.IsAliveSecureAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pike13Zoom.Blueface.IsAliveSecureResponse> IsAliveSecureAsync(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader) {
            Pike13Zoom.Blueface.IsAliveSecureRequest inValue = new Pike13Zoom.Blueface.IsAliveSecureRequest();
            inValue.SoapAuthHeader = SoapAuthHeader;
            return ((Pike13Zoom.Blueface.SMSAppSOAPProxySoap)(this)).IsAliveSecureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Pike13Zoom.Blueface.SendSMSResponse Pike13Zoom.Blueface.SMSAppSOAPProxySoap.SendSMS(Pike13Zoom.Blueface.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader, string destination, string message) {
            Pike13Zoom.Blueface.SendSMSRequest inValue = new Pike13Zoom.Blueface.SendSMSRequest();
            inValue.SoapAuthHeader = SoapAuthHeader;
            inValue.destination = destination;
            inValue.message = message;
            Pike13Zoom.Blueface.SendSMSResponse retVal = ((Pike13Zoom.Blueface.SMSAppSOAPProxySoap)(this)).SendSMS(inValue);
            return retVal.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pike13Zoom.Blueface.SendSMSResponse> Pike13Zoom.Blueface.SMSAppSOAPProxySoap.SendSMSAsync(Pike13Zoom.Blueface.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pike13Zoom.Blueface.SendSMSResponse> SendSMSAsync(Pike13Zoom.Blueface.SoapAuthHeader SoapAuthHeader, string destination, string message) {
            Pike13Zoom.Blueface.SendSMSRequest inValue = new Pike13Zoom.Blueface.SendSMSRequest();
            inValue.SoapAuthHeader = SoapAuthHeader;
            inValue.destination = destination;
            inValue.message = message;
            return ((Pike13Zoom.Blueface.SMSAppSOAPProxySoap)(this)).SendSMSAsync(inValue);
        }
    }
}
